export const LOAD_OUTCOME_TOKEN = 'outcome/LOAD_DATA_ITEM';
export const LOAD_OUTCOME_TOKEN_SUCCESS = 'outcome/LOAD_DATA_ITEM_SUCCESS';
export const LOAD_OUTCOME_TOKEN_FAILURE = 'outcome/LOAD_DATA_ITEM_FAILURE';

export const FETCH_OUTCOME_RESULT = 'outcome/FETCH_RESULT';
export const FETCH_OUTCOME_RESULT_SUCCESS = 'outcome/FETCH_RESULT_SUCCESS';
export const FETCH_OUTCOME_RESULT_FAILURE = 'outcome/FETCH_RESULT_FAILURE';

export const CLEAR_OUTCOME_CHOICES = 'outcome/CLEAR_CHOICES';

export const CHOOSE_PLANET = 'outcome/SELECT_FIRST_DATA_ITEM';
export const CHOOSE_VEHICLE = 'outcome/SELECT_SECOND_DATA_ITEM';
