export const LOAD_PLANETS_DATA = 'planets/LOAD_DATA_BUNCH';
export const LOAD_PLANETS_DATA_SUCCESS = 'planets/LOAD_DATA_BUNCH_SUCCESS';
export const LOAD_PLANETS_DATA_FAILURE = 'planets/LOAD_DATA_BUNCH_FAILURE';

export const CLEAR_PLANET_ITEMS = 'planets/CLEAR_DATA_BUNCH';
